project:
  type: website

website:
  title: "EPM SQUARE ANALYTICS"
  site-url: https://epm-square-analytics.netlify.app/
  description: "We provide programming services to both data science and clinical trials analysis"
  favicon: images/favicon.ico
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
      - text: "Consulting Services"
        icon: kanban
        href: consult_services/consulting_services1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

