project:
  type: website

website:
  title: "EPM SQUARE ANALYTICS"
  site-url: https://epm-square-analytics.netlify.app/
  description: "We provide training and consulting services to clients in various industries."
  favicon: images/favicon.ico
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
      - text: "Consulting Services"
        icon: kanban
        href: consult_services/consulting_services1.qmd
        
      - text: "Training Services"
        icon: kanban
        href: training_services/training_services.qmd
        
      - text: "Company Profile"
        icon: kanban
        href: company_profile/company_profile.qmd
        
      - text: "Sample Works"
        icon: kanban
        href: sample_works/sample_works.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

