---
pagetitle: "Sample Works | EPM SQUARE ANALYTICS"
title: "Sample Works"
---

## Sample works

This section contains sample projects that we have delivered to clients in the past. This section is meant to give you an overview into our philosophy and approach to projects. These projects range from data analysis reports, Rshiny applications, Dashboards etc.

## Companies that we have worked with

We have worked with research based companies like DTE Consultancy, Betting solutions Kenya, ABC Realtors among others.

## Sample 01

In this project, the client sought a way to explore various statistical models to gain a deeper understanding of their data. Initially, they were estimating multiple models using Excel. We proposed an interactive solution—a Shiny app in R—that allows for more efficient model exploration.

The app offers a wide range of modeling options, including time series models, OLS regression, machine learning models, simplex regression, constrained regression, instrumental variable regression, Kalman filter models, and more.

This work is still in progress - the client still wants more features to be added and we are working on that.

Here is the link to the live app : <https://4lt3sb-eric-odongo.shinyapps.io/shinyApp/>

## Sample 02

The client wanted a detailed analysis of their data using Structural Equation Modeling technique. The analysis was carried out using R software package.

Extensive analysis was conducted, including descriptive analysis, visualizations, and statistical modeling. Assumptions of the model were tested thoroughly.

A link to the pdf report is here : <https://github.com/rikoprogrammer/SEM_analysis/blob/main/SEM_analysis.pdf>

## Sample 03

A corporate client in Hargeisa, Somaliland, sought a comprehensive business plan for their new medical facility, **Holistic Health Center** ([www.holistichealth.com](http://www.holistichealth.com)). We developed a detailed business plan and delivered it on time to support their business operations and ensure a smooth setup.

## Sample 04

## Sample 05
